import { Prompt, PromptVersion } from './types';

// Helper function to extract variables from prompt text
const extractVariables = (text: string): string[] => {
  const regex = /\{\{\s*(\w+)\s*\}\}/g;
  const matches = text.matchAll(regex);
  return [...new Set(Array.from(matches, m => m[1]))];
};

// Mock prompt data for 10 business use cases
export const mockPrompts: Prompt[] = [
  {
    id: 'prompt-1',
    name: 'Customer Service Response',
    description: 'Automated response template for customer service inquiries',
    latestVersion: '2.0',
    lastModified: new Date('2025-12-10T14:30:00'),
    createdDate: new Date('2025-11-15T09:00:00'),
    commitMessage: 'Added empathy statements',
    alias: 'cs-response',
    tags: ['customer-service', 'support', 'communication'],
    project: 'Project X',
    versions: [
      {
        id: 'v1-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-11-15T09:00:00'),
        promptText: 'You are a customer service agent. Respond to {{ customer_name }}\'s inquiry about {{ issue_type }}. Be professional and helpful.',
        promptType: 'text',
        variables: ['customer_name', 'issue_type'],
        aliases: [],
        metadata: {},
        commitMessage: 'Initial version',
      },
      {
        id: 'v1-2',
        versionNumber: '2.0',
        registeredAt: new Date('2025-12-10T14:30:00'),
        promptText: 'You are a compassionate customer service agent. Address {{ customer_name }} by name and acknowledge their frustration regarding {{ issue_type }}. Provide a clear solution and follow-up steps. Show empathy and maintain a professional tone.',
        promptType: 'text',
        variables: ['customer_name', 'issue_type'],
        aliases: ['cs-v2'],
        metadata: { quality: 'high' },
        commitMessage: 'Added empathy statements and structured response',
      },
    ],
  },
  {
    id: 'prompt-2',
    name: 'Product Documentation Generator',
    description: 'Generate comprehensive product documentation from specifications',
    latestVersion: '1.1',
    lastModified: new Date('2025-12-08T16:45:00'),
    createdDate: new Date('2025-11-20T10:30:00'),
    commitMessage: 'Added examples section',
    tags: ['documentation', 'technical-writing', 'product'],
    project: 'Project X',
    versions: [
      {
        id: 'v2-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-11-20T10:30:00'),
        promptText: 'Create technical documentation for {{ product_name }}. Include overview, features, and usage instructions for {{ target_audience }}.',
        promptType: 'text',
        variables: ['product_name', 'target_audience'],
        aliases: [],
        metadata: {},
        commitMessage: 'Initial documentation template',
      },
      {
        id: 'v2-2',
        versionNumber: '1.1',
        registeredAt: new Date('2025-12-08T16:45:00'),
        promptText: 'Create comprehensive technical documentation for {{ product_name }}. Target audience: {{ target_audience }}.\n\nStructure:\n1. Overview and key benefits\n2. Features and capabilities\n3. Getting started guide\n4. Usage examples\n5. Troubleshooting common issues\n\nUse clear headings, bullet points, and code examples where applicable.',
        promptType: 'text',
        variables: ['product_name', 'target_audience'],
        aliases: ['prod-docs'],
        metadata: { format: 'markdown' },
        commitMessage: 'Added structured sections and examples',
      },
    ],
  },
  {
    id: 'prompt-3',
    name: 'Sales Email Composer',
    description: 'Personalized sales outreach email template',
    latestVersion: '3.0',
    lastModified: new Date('2025-12-11T11:20:00'),
    createdDate: new Date('2025-11-10T13:00:00'),
    commitMessage: 'Optimized for engagement',
    alias: 'sales-outreach',
    tags: ['sales', 'email', 'outreach', 'marketing'],
    project: 'Project Y',
    versions: [
      {
        id: 'v3-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-11-10T13:00:00'),
        promptText: 'Write a sales email to {{ prospect_name }} at {{ company_name }} about {{ product_name }}.',
        promptType: 'text',
        variables: ['prospect_name', 'company_name', 'product_name'],
        aliases: [],
        metadata: {},
        commitMessage: 'Basic sales template',
      },
      {
        id: 'v3-2',
        versionNumber: '2.0',
        registeredAt: new Date('2025-11-28T09:15:00'),
        promptText: 'Compose a personalized sales email to {{ prospect_name }} at {{ company_name }}. Highlight how {{ product_name }} solves {{ pain_point }}. Include a clear call-to-action.',
        promptType: 'text',
        variables: ['prospect_name', 'company_name', 'product_name', 'pain_point'],
        aliases: [],
        metadata: {},
        commitMessage: 'Added pain point and CTA',
      },
      {
        id: 'v3-3',
        versionNumber: '3.0',
        registeredAt: new Date('2025-12-11T11:20:00'),
        promptText: 'You are a sales development representative. Write a compelling, personalized email to {{ prospect_name }}, {{ job_title }} at {{ company_name }}.\n\nOpening: Reference {{ common_interest }} or recent {{ company_news }}.\nValue Proposition: Explain how {{ product_name }} addresses {{ pain_point }} specifically for companies in {{ industry }}.\nSocial Proof: Mention that {{ similar_company }} achieved {{ result }} using our solution.\nCall-to-Action: Request a brief 15-minute call to discuss {{ specific_topic }}.\n\nTone: Professional, conversational, and value-focused. Limit to 150 words.',
        promptType: 'text',
        variables: ['prospect_name', 'job_title', 'company_name', 'common_interest', 'company_news', 'product_name', 'pain_point', 'industry', 'similar_company', 'result', 'specific_topic'],
        aliases: ['sales-v3'],
        metadata: { quality: 'high', conversion_rate: 'optimized' },
        commitMessage: 'Optimized for engagement with social proof',
      },
    ],
  },
  {
    id: 'prompt-4',
    name: 'Data Analysis Report',
    description: 'Generate insights and visualizations from data analysis',
    latestVersion: '1.0',
    lastModified: new Date('2025-12-05T15:30:00'),
    createdDate: new Date('2025-12-05T15:30:00'),
    tags: ['analytics', 'reporting', 'data-science'],
    project: 'Project X',
    versions: [
      {
        id: 'v4-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-12-05T15:30:00'),
        promptText: 'Analyze the {{ dataset_name }} dataset focusing on {{ key_metrics }}. Provide insights on trends, anomalies, and actionable recommendations for {{ stakeholder_group }}. Include:\n\n1. Executive Summary\n2. Key Findings\n3. Trend Analysis\n4. Recommendations\n5. Next Steps\n\nFormat: {{ output_format }}',
        promptType: 'text',
        variables: ['dataset_name', 'key_metrics', 'stakeholder_group', 'output_format'],
        aliases: [],
        metadata: {},
        commitMessage: 'Initial analytics template',
      },
    ],
  },
  {
    id: 'prompt-5',
    name: 'Meeting Summary Assistant',
    description: 'Summarize meeting notes with action items',
    latestVersion: '2.0',
    lastModified: new Date('2025-12-09T10:00:00'),
    createdDate: new Date('2025-11-25T14:00:00'),
    commitMessage: 'Added decision tracking',
    tags: ['meetings', 'productivity', 'notes'],
    project: 'Project Y',
    versions: [
      {
        id: 'v5-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-11-25T14:00:00'),
        promptText: 'Summarize the meeting about {{ meeting_topic }}. List key discussion points and action items assigned to {{ attendees }}.',
        promptType: 'text',
        variables: ['meeting_topic', 'attendees'],
        aliases: [],
        metadata: {},
        commitMessage: 'Basic meeting summary',
      },
      {
        id: 'v5-2',
        versionNumber: '2.0',
        registeredAt: new Date('2025-12-09T10:00:00'),
        promptText: 'Create a structured summary of the {{ meeting_type }} meeting about {{ meeting_topic }} held on {{ date }}.\n\nInclude:\n- Attendees: {{ attendees }}\n- Key Discussion Points (bullet format)\n- Decisions Made\n- Action Items (with owner and due date)\n- Open Questions\n- Next Meeting Date\n\nFormat for clarity and easy distribution.',
        promptType: 'text',
        variables: ['meeting_type', 'meeting_topic', 'date', 'attendees'],
        aliases: ['meeting-notes'],
        metadata: {},
        commitMessage: 'Added decision tracking and structured format',
      },
    ],
  },
  {
    id: 'prompt-6',
    name: 'Code Review Assistant',
    description: 'AI-powered code review with best practice suggestions',
    latestVersion: '1.0',
    lastModified: new Date('2025-12-07T13:45:00'),
    createdDate: new Date('2025-12-07T13:45:00'),
    tags: ['development', 'code-review', 'quality-assurance'],
    project: 'Project X',
    versions: [
      {
        id: 'v6-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-12-07T13:45:00'),
        promptText: 'Review the {{ programming_language }} code for {{ feature_name }}. Focus on:\n\n1. Code quality and readability\n2. Potential bugs or edge cases\n3. Performance optimization opportunities\n4. Security vulnerabilities\n5. Adherence to {{ coding_standards }} standards\n6. Test coverage gaps\n\nProvide specific, actionable feedback with code examples where helpful.',
        promptType: 'text',
        variables: ['programming_language', 'feature_name', 'coding_standards'],
        aliases: [],
        metadata: {},
        commitMessage: 'Initial code review template',
      },
    ],
  },
  {
    id: 'prompt-7',
    name: 'Marketing Content Creator',
    description: 'Generate engaging marketing copy for various channels',
    latestVersion: '2.1',
    lastModified: new Date('2025-12-12T09:30:00'),
    createdDate: new Date('2025-11-18T11:00:00'),
    commitMessage: 'Added SEO optimization',
    tags: ['marketing', 'content', 'copywriting', 'seo'],
    project: 'Project Y',
    versions: [
      {
        id: 'v7-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-11-18T11:00:00'),
        promptText: 'Create marketing content for {{ product_name }} targeting {{ audience }}. Channel: {{ platform }}.',
        promptType: 'text',
        variables: ['product_name', 'audience', 'platform'],
        aliases: [],
        metadata: {},
        commitMessage: 'Basic marketing template',
      },
      {
        id: 'v7-2',
        versionNumber: '2.0',
        registeredAt: new Date('2025-12-01T14:20:00'),
        promptText: 'Create compelling marketing content for {{ product_name }}.\n\nTarget Audience: {{ audience }}\nPlatform: {{ platform }}\nTone: {{ brand_voice }}\nKey Message: {{ value_proposition }}\nCall-to-Action: {{ cta }}\n\nGuidelines:\n- Highlight benefits, not just features\n- Use power words and emotional triggers\n- Keep it concise and scannable\n- Include social proof if available',
        promptType: 'text',
        variables: ['product_name', 'audience', 'platform', 'brand_voice', 'value_proposition', 'cta'],
        aliases: [],
        metadata: {},
        commitMessage: 'Enhanced with brand voice and CTA',
      },
      {
        id: 'v7-3',
        versionNumber: '2.1',
        registeredAt: new Date('2025-12-12T09:30:00'),
        promptText: 'Create SEO-optimized marketing content for {{ product_name }}.\n\nTarget Audience: {{ audience }}\nPlatform: {{ platform }}\nPrimary Keyword: {{ keyword }}\nTone: {{ brand_voice }}\nKey Message: {{ value_proposition }}\nCall-to-Action: {{ cta }}\n\nGuidelines:\n- Naturally incorporate {{ keyword }} and related terms\n- Highlight benefits and unique selling points\n- Use persuasive language and emotional triggers\n- Structure with clear headings (H2, H3)\n- Include meta description (under 160 chars)\n- Optimize for {{ character_limit }} character limit',
        promptType: 'text',
        variables: ['product_name', 'audience', 'platform', 'keyword', 'brand_voice', 'value_proposition', 'cta', 'character_limit'],
        aliases: ['marketing-seo'],
        metadata: { seo: 'optimized' },
        commitMessage: 'Added SEO optimization and keyword focus',
      },
    ],
  },
  {
    id: 'prompt-8',
    name: 'Technical Support Response',
    description: 'Troubleshooting guide for technical support tickets',
    latestVersion: '1.1',
    lastModified: new Date('2025-12-06T16:15:00'),
    createdDate: new Date('2025-11-22T10:00:00'),
    commitMessage: 'Added escalation criteria',
    tags: ['support', 'troubleshooting', 'technical'],
    project: 'Project X',
    versions: [
      {
        id: 'v8-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-11-22T10:00:00'),
        promptText: 'You are a technical support specialist. Help {{ customer_name }} resolve {{ issue_description }} with {{ product_name }}. Provide step-by-step troubleshooting instructions.',
        promptType: 'chat',
        variables: ['customer_name', 'issue_description', 'product_name'],
        aliases: [],
        metadata: {},
        commitMessage: 'Initial support template',
      },
      {
        id: 'v8-2',
        versionNumber: '1.1',
        registeredAt: new Date('2025-12-06T16:15:00'),
        promptText: 'You are a technical support specialist assisting {{ customer_name }} with {{ issue_description }} related to {{ product_name }}.\n\nApproach:\n1. Acknowledge the issue and reassure the customer\n2. Gather relevant information ({{ system_info }})\n3. Provide clear, numbered troubleshooting steps\n4. Explain what each step does\n5. Ask for confirmation after each major step\n6. If unresolved after 3 steps, escalate to {{ escalation_team }}\n\nTone: Patient, clear, and technical but accessible.',
        promptType: 'chat',
        variables: ['customer_name', 'issue_description', 'product_name', 'system_info', 'escalation_team'],
        aliases: ['tech-support'],
        metadata: {},
        commitMessage: 'Added escalation criteria and structured approach',
      },
    ],
  },
  {
    id: 'prompt-9',
    name: 'Contract Analysis Assistant',
    description: 'Extract key terms and risks from legal contracts',
    latestVersion: '1.0',
    lastModified: new Date('2025-12-04T12:00:00'),
    createdDate: new Date('2025-12-04T12:00:00'),
    tags: ['legal', 'contracts', 'analysis', 'compliance'],
    project: 'Project Y',
    versions: [
      {
        id: 'v9-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-12-04T12:00:00'),
        promptText: 'Analyze the {{ contract_type }} contract and provide a summary report.\n\nExtract and highlight:\n1. Key Terms & Conditions\n2. Parties Involved\n3. Duration and Renewal Terms\n4. Payment Terms\n5. Termination Clauses\n6. Liability and Indemnification\n7. Potential Risks or Red Flags\n8. Compliance Requirements\n\nFocus area: {{ focus_area }}\nJurisdiction: {{ jurisdiction }}\n\nFormat as a structured report suitable for {{ stakeholder }} review.',
        promptType: 'text',
        variables: ['contract_type', 'focus_area', 'jurisdiction', 'stakeholder'],
        aliases: [],
        metadata: {},
        commitMessage: 'Contract analysis template',
      },
    ],
  },
  {
    id: 'prompt-10',
    name: 'Invoice Processing Assistant',
    description: 'Extract and validate invoice data for accounting',
    latestVersion: '2.0',
    lastModified: new Date('2025-12-11T15:45:00'),
    createdDate: new Date('2025-11-30T09:30:00'),
    commitMessage: 'Added validation rules',
    tags: ['finance', 'accounting', 'automation', 'data-extraction'],
    project: 'Project X',
    versions: [
      {
        id: 'v10-1',
        versionNumber: '1.0',
        registeredAt: new Date('2025-11-30T09:30:00'),
        promptText: 'Extract key information from the {{ vendor_name }} invoice:\n\n- Invoice Number\n- Date\n- Vendor Details\n- Line Items with descriptions and amounts\n- Subtotal, Tax, Total\n- Payment Terms\n- Due Date',
        promptType: 'text',
        variables: ['vendor_name'],
        aliases: [],
        metadata: {},
        commitMessage: 'Basic invoice extraction',
      },
      {
        id: 'v10-2',
        versionNumber: '2.0',
        registeredAt: new Date('2025-12-11T15:45:00'),
        promptText: 'Process and validate invoice from {{ vendor_name }} against purchase order {{ po_number }}.\n\nExtract:\n- Invoice Number\n- Invoice Date\n- Vendor Details (name, address, tax ID)\n- Line Items (description, quantity, unit price, total)\n- Subtotal, Tax ({{ tax_rate }}%), Total Amount\n- Payment Terms\n- Due Date\n\nValidation:\n- Verify amounts match PO {{ po_number }}\n- Check tax calculation is correct\n- Confirm vendor is approved in system\n- Flag if total exceeds {{ budget_threshold }}\n- Verify payment terms align with contract\n\nOutput: Structured JSON format with validation status and any discrepancies.',
        promptType: 'text',
        variables: ['vendor_name', 'po_number', 'tax_rate', 'budget_threshold'],
        aliases: ['invoice-proc'],
        metadata: { automation: 'enabled' },
        commitMessage: 'Added validation rules and PO matching',
      },
    ],
  },
];

// Update variables array when creating versions
mockPrompts.forEach(prompt => {
  prompt.versions.forEach(version => {
    version.variables = extractVariables(version.promptText);
  });
});

export default mockPrompts;

